server:
  port: 8081

spring:
  application:
    name: cloud_storage
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
