server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.16.4.246:8848
  application:
    name: CloudStorage
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

aliyun:
  keyid: LTAI5tBpdi38sJNa7iZaKzP7
  keysecret: sVTw4QTQRJVQOOc5vVQ8ECKN0Iju1G
  bucketname: opencurve-picture
  endpoint: oss-cn-shenzhen.aliyuncs.com