server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.16.4.246:8848
  application:
    name: education
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://10.16.4.246:5432/opencurve
      username: postgres
      password: 123456

      #配置连接池大小参数
      initial-size: 15
      min-idle: 10
      max-active: 50

      #配置最长等待时间
      max-wait: 30000

      #连接最小生存时间
      min-evictable-idle-time-millis: 30000


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher





mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sustech.service_education.entity




